project_name: pulsargateway
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: .
    binary: pulsargateway
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.Branch=main
      - -X github.com/prometheus/common/version.Revision={{.ShortCommit}}
      - -X github.com/prometheus/common/version.BuildUser=transnano
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
nfpms:
  - id: pulsargateway-nfpms
    package_name: pulsargateway
    homepage: https://github.com/transnano/pulsargateway
    maintainer: Transnano <transnano.jp@gmail.com>
    description: Publish acceptor for ephemeral and batch jobs.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
